MenuBar = new Object();

MenuBar.menuBar6= function() {
	var menus = new Array();
	var m0 = new MenuItem("In\u00EDcio", null, null, null, "./", null, null, null, null, null);
	menus.push(m0);
	var m1 = new MenuItem("Administra\u00E7\u00E3o", null, null, null, null, null, null, null, null, null);
	menus.push(m1);
	var m1_0 = new MenuItem("Documentos\/Infra\u00E7\u00F5es", null, null, null, null, null, null, null, null, null);
	m1_0.setParentMenuItem(m1);
	var m1_0_0 = new MenuItem("Tipo Documento", null, null, null, null, null, null, null, null, null);
	m1_0_0.setParentMenuItem(m1_0);
	var m1_0_0_0 = new MenuItem("Consultar", null, null, null, null, null, null, null, null, null);
	m1_0_0_0.setParentMenuItem(m1_0_0);
	var m1_0_0_1 = new MenuItem("Incluir", null, null, null, null, null, null, null, null, null);
	m1_0_0_1.setParentMenuItem(m1_0_0);
	var m1_0_1 = new MenuItem("Penalidades", null, null, null, null, null, null, null, null, null);
	m1_0_1.setParentMenuItem(m1_0);
	var m1_0_1_0 = new MenuItem("Consultar", null, null, null, null, null, null, null, null, null);
	m1_0_1_0.setParentMenuItem(m1_0_1);
	var m1_0_1_1 = new MenuItem("Incluir", null, null, null, null, null, null, null, null, null);
	m1_0_1_1.setParentMenuItem(m1_0_1);
	var m1_0_2 = new MenuItem("Tipo de Infra\u00E7\u00E3o", null, null, null, null, null, null, null, null, null);
	m1_0_2.setParentMenuItem(m1_0);
	var m1_0_2_0 = new MenuItem("Consultar", null, null, null, null, null, null, null, null, null);
	m1_0_2_0.setParentMenuItem(m1_0_2);
	var m1_0_2_1 = new MenuItem("Incluir", null, null, null, null, null, null, null, null, null);
	m1_0_2_1.setParentMenuItem(m1_0_2);
	var m1_0_3 = new MenuItem("Documentos Exigidos", null, null, null, null, null, null, null, null, null);
	m1_0_3.setParentMenuItem(m1_0);
	var m1_0_3_0 = new MenuItem("Gerenciar Documentos", null, null, null, null, null, null, null, null, null);
	m1_0_3_0.setParentMenuItem(m1_0_3);
	var m1_1 = new MenuItem("Cadastro de Agentes", null, null, null, null, null, null, null, null, null);
	m1_1.setParentMenuItem(m1);
	var m1_1_0 = new MenuItem("Bolsa \/ Associa\u00E7\u00E3o", null, null, null, null, null, null, null, null, null);
	m1_1_0.setParentMenuItem(m1_1);
	var m1_1_0_0 = new MenuItem("Consultar", null, null, null, null, null, null, null, null, null);
	m1_1_0_0.setParentMenuItem(m1_1_0);
	var m1_1_0_1 = new MenuItem("Incluir", null, null, null, null, null, null, null, null, null);
	m1_1_0_1.setParentMenuItem(m1_1_0);
	var m1_1_1 = new MenuItem("Corretor \/ Corretora", null, null, null, null, null, null, null, null, null);
	m1_1_1.setParentMenuItem(m1_1);
	var m1_1_1_0 = new MenuItem("Consultar", null, null, null, null, null, null, null, null, null);
	m1_1_1_0.setParentMenuItem(m1_1_1);
	var m1_1_1_1 = new MenuItem("Incluir", null, null, null, null, null, null, null, null, null);
	m1_1_1_1.setParentMenuItem(m1_1_1);
	var m1_2 = new MenuItem("Configura\u00E7\u00E3o", null, null, null, null, null, null, null, null, null);
	m1_2.setParentMenuItem(m1);
	var m1_2_0 = new MenuItem("Opera\u00E7\u00E3o", null, null, null, null, null, null, null, null, null);
	m1_2_0.setParentMenuItem(m1_2);
	var m1_2_0_0 = new MenuItem("Consultar", null, null, null, null, null, null, null, null, null);
	m1_2_0_0.setParentMenuItem(m1_2_0);
	var m1_2_1 = new MenuItem("Manter Mensagem", null, null, null, null, null, null, null, null, null);
	m1_2_1.setParentMenuItem(m1_2);
	var m1_2_1_0 = new MenuItem("Consultar", null, null, null, null, null, null, null, null, null);
	m1_2_1_0.setParentMenuItem(m1_2_1);
	var m1_2_1_1 = new MenuItem("Incluir", null, null, null, null, null, null, null, null, null);
	m1_2_1_1.setParentMenuItem(m1_2_1);
	var m1_2_2 = new MenuItem("Manter Tipo Ofertante", null, null, null, null, null, null, null, null, null);
	m1_2_2.setParentMenuItem(m1_2);
	var m1_2_2_0 = new MenuItem("Consultar", null, null, null, null, null, null, null, null, null);
	m1_2_2_0.setParentMenuItem(m1_2_2);
	var m1_2_2_1 = new MenuItem("Incluir", null, null, null, null, null, null, null, null, null);
	m1_2_2_1.setParentMenuItem(m1_2_2);
	var m1_2_3 = new MenuItem("Manter Sigla Produto", null, null, null, null, null, null, null, null, null);
	m1_2_3.setParentMenuItem(m1_2);
	var m1_2_3_0 = new MenuItem("Consultar", null, null, null, null, null, null, null, null, null);
	m1_2_3_0.setParentMenuItem(m1_2_3);
	var m1_2_3_1 = new MenuItem("Incluir", null, null, null, null, null, null, null, null, null);
	m1_2_3_1.setParentMenuItem(m1_2_3);
	var m2 = new MenuItem("Pr\u00E9-leil\u00E3o", null, null, null, null, null, null, null, null, null);
	menus.push(m2);
	var m2_0 = new MenuItem("Cadastro de Aviso\/Edital", null, null, null, null, null, null, null, null, null);
	m2_0.setParentMenuItem(m2);
	var m2_0_0 = new MenuItem("Manter Aviso\/Edital", null, null, null, null, null, null, null, null, null);
	m2_0_0.setParentMenuItem(m2_0);
	var m2_0_0_0 = new MenuItem("Consultar", null, null, null, null, null, null, null, null, null);
	m2_0_0_0.setParentMenuItem(m2_0_0);
	var m2_0_0_1 = new MenuItem("Incluir", null, null, null, null, null, null, null, null, null);
	m2_0_0_1.setParentMenuItem(m2_0_0);
	var m2_1 = new MenuItem("Cadastro de Template", null, null, null, null, null, null, null, null, null);
	m2_1.setParentMenuItem(m2);
	var m2_1_0 = new MenuItem("Manter Template", null, null, null, null, null, null, null, null, null);
	m2_1_0.setParentMenuItem(m2_1);
	var m2_1_0_0 = new MenuItem("Consultar", null, null, null, null, null, null, null, null, null);
	m2_1_0_0.setParentMenuItem(m2_1_0);
	var m2_1_0_1 = new MenuItem("Incluir", null, null, null, null, null, null, null, null, null);
	m2_1_0_1.setParentMenuItem(m2_1_0);
	var m2_2 = new MenuItem("Cadastro de Comunicado", null, null, null, null, null, null, null, null, null);
	m2_2.setParentMenuItem(m2);
	var m2_2_0 = new MenuItem("Manter Comunicado", null, null, null, null, null, null, null, null, null);
	m2_2_0.setParentMenuItem(m2_2);
	var m2_2_0_0 = new MenuItem("Consultar", null, null, null, null, null, null, null, null, null);
	m2_2_0_0.setParentMenuItem(m2_2_0);
	var m2_2_0_1 = new MenuItem("Incluir", null, null, null, null, null, null, null, null, null);
	m2_2_0_1.setParentMenuItem(m2_2_0);
	var m3 = new MenuItem("Leil\u00E3o", null, null, null, null, null, null, null, null, null);
	menus.push(m3);
	var m4 = new MenuItem("P\u00F3s-leil\u00E3o", null, null, null, null, null, null, null, null, null);
	menus.push(m4);
	var factorymenuPrincipal = new FactoryMenu(menus, "menuPrincipal", "menuPrincipal", "top");
	factorymenuPrincipal.addNivel(new Nivel(true, "menuNivel1", "menuNivel1-Hover", null, 120, 20, false, false, false));
	factorymenuPrincipal.addNivel(new Nivel(true, "menuNivel2", "menuNivel2-Hover", null, null, null, false, false, false));
	factorymenuPrincipal.addNivel(new Nivel(true, "menuNivel3", "menuNivel3", null, null, null, false, true, true));
	factorymenuPrincipal.addNivel(new Nivel(false, "menuNivel4", "menuNivel4", null, null, null, false, true, false));
	factorymenuPrincipal.construirMenu();
};
